parser: '@typescript-eslint/parser'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
ignorePatterns:
  - '*.js'
  - node_modules/
env:
  node: true
  es2020: true
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  '@typescript-eslint/member-delimiter-style':
    - error
    - multiline:
        delimiter: none
  '@typescript-eslint/no-non-null-assertion':
    - error
